// Package postgres is the persistence layer for QueueForge jobs.
//
// All durable state of record lives here. The repository exposes the
// operations every service needs: insert, fetch, transition, claim, release,
// scan for due/expired jobs, and aggregate metrics. Concurrent transitions
// are made safe with SELECT … FOR UPDATE SKIP LOCKED on the hot paths.
package postgres

import (
	"context"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"sort"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/queueforge/queueforge/internal/job"
)

//go:embed migrations/*.sql
var migrationsFS embed.FS

// MigrationsFS exposes the embedded migrations so callers (or external tools)
// can apply them without depending on the on-disk migrations/ directory.
func MigrationsFS() fs.FS { return migrationsFS }

// ErrNotFound is returned when a single-row lookup matches nothing.
var ErrNotFound = errors.New("job not found")

// ErrDuplicate is returned when the unique dedup index rejects an insert.
var ErrDuplicate = errors.New("duplicate job")

const uniqueViolationCode = "23505"

// Repo wraps a pgxpool with QueueForge-specific operations.
type Repo struct {
	pool *pgxpool.Pool
}

// New opens a connection pool against dsn and pings it.
func New(ctx context.Context, dsn string, maxConns int32) (*Repo, error) {
	cfg, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		return nil, fmt.Errorf("parse postgres dsn: %w", err)
	}
	if maxConns > 0 {
		cfg.MaxConns = maxConns
	}
	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("open postgres pool: %w", err)
	}
	pingCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()
	if err := pool.Ping(pingCtx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("ping postgres: %w", err)
	}
	return &Repo{pool: pool}, nil
}

// Close releases connections.
func (r *Repo) Close() { r.pool.Close() }

// Pool exposes the underlying pgxpool for advanced callers (admin endpoints,
// tests). Most code should prefer the typed methods on Repo.
func (r *Repo) Pool() *pgxpool.Pool { return r.pool }

// Migrate applies any embedded migrations whose name is not in the
// schema_migrations table. The implementation is intentionally minimal — no
// down migrations, no checksum verification — because the schema is small and
// the embedded files are the source of truth.
func (r *Repo) Migrate(ctx context.Context) error {
	if _, err := r.pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS schema_migrations (
			name        TEXT PRIMARY KEY,
			applied_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
		)
	`); err != nil {
		return fmt.Errorf("ensure schema_migrations: %w", err)
	}

	entries, err := fs.ReadDir(migrationsFS, "migrations")
	if err != nil {
		return fmt.Errorf("read embedded migrations: %w", err)
	}

	var ups []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		if !strings.HasSuffix(e.Name(), ".up.sql") {
			continue
		}
		ups = append(ups, e.Name())
	}
	sort.Strings(ups)

	for _, name := range ups {
		var exists bool
		if err := r.pool.QueryRow(ctx,
			`SELECT EXISTS(SELECT 1 FROM schema_migrations WHERE name=$1)`, name,
		).Scan(&exists); err != nil {
			return fmt.Errorf("check migration %s: %w", name, err)
		}
		if exists {
			continue
		}

		sqlBytes, err := migrationsFS.ReadFile("migrations/" + name)
		if err != nil {
			return fmt.Errorf("read migration %s: %w", name, err)
		}

		tx, err := r.pool.Begin(ctx)
		if err != nil {
			return fmt.Errorf("begin migration %s: %w", name, err)
		}
		if _, err := tx.Exec(ctx, string(sqlBytes)); err != nil {
			_ = tx.Rollback(ctx)
			return fmt.Errorf("apply migration %s: %w", name, err)
		}
		if _, err := tx.Exec(ctx,
			`INSERT INTO schema_migrations(name) VALUES ($1)`, name,
		); err != nil {
			_ = tx.Rollback(ctx)
			return fmt.Errorf("record migration %s: %w", name, err)
		}
		if err := tx.Commit(ctx); err != nil {
			return fmt.Errorf("commit migration %s: %w", name, err)
		}
	}
	return nil
}

// Insert creates a new job row. The job's ID is generated by the database if
// the caller did not supply one.
func (r *Repo) Insert(ctx context.Context, j *job.Job) error {
	if j.RetryPolicy.MaxAttempts < 0 {
		return job.ErrInvalidRetry
	}
	retry, err := json.Marshal(j.RetryPolicy)
	if err != nil {
		return fmt.Errorf("marshal retry policy: %w", err)
	}
	if len(j.Payload) == 0 {
		j.Payload = json.RawMessage(`{}`)
	}

	q := `
		INSERT INTO jobs (id, queue, job_type, priority, state, payload,
		                  dedup_key, dedup_mode, retry_policy, run_at)
		VALUES (COALESCE(NULLIF($1,'')::uuid, gen_random_uuid()),
		        $2, $3, $4, $5, $6, $7, $8, $9, $10)
		RETURNING id, created_at, updated_at
	`
	err = r.pool.QueryRow(ctx, q,
		j.ID, j.Queue, j.JobType, j.Priority, j.State, j.Payload,
		j.DedupKey, j.DedupMode, retry, j.RunAt,
	).Scan(&j.ID, &j.CreatedAt, &j.UpdatedAt)
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == uniqueViolationCode {
			return ErrDuplicate
		}
		return fmt.Errorf("insert job: %w", err)
	}
	return nil
}

// Get fetches a single job by id.
func (r *Repo) Get(ctx context.Context, id string) (*job.Job, error) {
	const q = `
		SELECT id, queue, job_type, priority, state, payload,
		       dedup_key, dedup_mode, retry_policy, attempts, last_error,
		       run_at, visibility_until, claimed_by,
		       created_at, updated_at, completed_at, result
		FROM jobs WHERE id = $1
	`
	row := r.pool.QueryRow(ctx, q, id)
	j, err := scanJob(row)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrNotFound
	}
	return j, err
}

// FindActiveByDedupKey returns an existing non-terminal job for the given
// (queue, key) tuple, if any. Used by the API to implement DedupReturnExisting.
func (r *Repo) FindActiveByDedupKey(ctx context.Context, queue, key string) (*job.Job, error) {
	const q = `
		SELECT id, queue, job_type, priority, state, payload,
		       dedup_key, dedup_mode, retry_policy, attempts, last_error,
		       run_at, visibility_until, claimed_by,
		       created_at, updated_at, completed_at, result
		FROM jobs
		WHERE queue = $1 AND dedup_key = $2
		  AND state IN ('pending','queued','running')
		LIMIT 1
	`
	row := r.pool.QueryRow(ctx, q, queue, key)
	j, err := scanJob(row)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrNotFound
	}
	return j, err
}

// MarkQueued transitions a pending job to queued after a successful Kafka
// publish. This is idempotent — re-running it for a job already in 'queued'
// has no effect.
func (r *Repo) MarkQueued(ctx context.Context, id string) error {
	const q = `
		UPDATE jobs
		SET state = 'queued', updated_at = NOW()
		WHERE id = $1 AND state = 'pending'
	`
	_, err := r.pool.Exec(ctx, q, id)
	return err
}

// ClaimResult is returned by Claim — the worker uses this to know how long it
// has before its lease expires.
type ClaimResult struct {
	Job             *job.Job
	VisibilityUntil time.Time
}

// Claim atomically transitions a job to running, recording the worker
// identifier and a visibility deadline. Returns ErrNotFound if the job is
// not currently claimable (terminal, missing, or already claimed).
//
// We accept both 'pending' and 'queued' to absorb a benign race: the
// scheduler can publish to Kafka and then crash before flipping the row to
// 'queued', leaving an on-Kafka message whose row is still 'pending'. The
// worker should still be able to process it.
func (r *Repo) Claim(ctx context.Context, id, workerID string, leaseFor time.Duration) (*ClaimResult, error) {
	const q = `
		UPDATE jobs
		SET state = 'running',
		    attempts = attempts + 1,
		    claimed_by = $2,
		    visibility_until = NOW() + ($3::text)::interval,
		    updated_at = NOW()
		WHERE id = $1 AND state IN ('pending','queued')
		RETURNING id, queue, job_type, priority, state, payload,
		          dedup_key, dedup_mode, retry_policy, attempts, last_error,
		          run_at, visibility_until, claimed_by,
		          created_at, updated_at, completed_at, result
	`
	row := r.pool.QueryRow(ctx, q, id, workerID, fmt.Sprintf("%d milliseconds", leaseFor.Milliseconds()))
	j, err := scanJob(row)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	return &ClaimResult{Job: j, VisibilityUntil: *j.VisibilityUntil}, nil
}

// ExtendLease pushes the visibility deadline forward; used by worker heartbeats.
func (r *Repo) ExtendLease(ctx context.Context, id, workerID string, leaseFor time.Duration) error {
	const q = `
		UPDATE jobs
		SET visibility_until = NOW() + ($3::text)::interval,
		    updated_at = NOW()
		WHERE id = $1 AND state = 'running' AND claimed_by = $2
	`
	tag, err := r.pool.Exec(ctx, q, id, workerID, fmt.Sprintf("%d milliseconds", leaseFor.Milliseconds()))
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// Succeeded transitions running → succeeded with an optional result payload.
func (r *Repo) Succeeded(ctx context.Context, id, workerID string, result json.RawMessage) error {
	if len(result) == 0 {
		result = json.RawMessage(`null`)
	}
	const q = `
		UPDATE jobs
		SET state = 'succeeded',
		    result = $3,
		    completed_at = NOW(),
		    visibility_until = NULL,
		    claimed_by = NULL,
		    updated_at = NOW()
		WHERE id = $1 AND state = 'running' AND claimed_by = $2
	`
	tag, err := r.pool.Exec(ctx, q, id, workerID, result)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// MarkPendingRetry sends a running job back to pending with a future run_at.
// The scheduler will promote it back into Kafka when due.
func (r *Repo) MarkPendingRetry(ctx context.Context, id, workerID string, runAt time.Time, lastErr string) error {
	const q = `
		UPDATE jobs
		SET state = 'pending',
		    run_at = $3,
		    last_error = $4,
		    visibility_until = NULL,
		    claimed_by = NULL,
		    updated_at = NOW()
		WHERE id = $1 AND state = 'running' AND claimed_by = $2
	`
	tag, err := r.pool.Exec(ctx, q, id, workerID, runAt, lastErr)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// DeadLetter marks the job as dead-lettered after retries are exhausted.
func (r *Repo) DeadLetter(ctx context.Context, id, workerID, lastErr string) error {
	const q = `
		UPDATE jobs
		SET state = 'dead_lettered',
		    last_error = $3,
		    completed_at = NOW(),
		    visibility_until = NULL,
		    claimed_by = NULL,
		    updated_at = NOW()
		WHERE id = $1 AND state = 'running' AND claimed_by = $2
	`
	tag, err := r.pool.Exec(ctx, q, id, workerID, lastErr)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// Cancel transitions any non-terminal job to cancelled.
func (r *Repo) Cancel(ctx context.Context, id string) error {
	const q = `
		UPDATE jobs
		SET state = 'cancelled',
		    completed_at = NOW(),
		    updated_at = NOW()
		WHERE id = $1 AND state IN ('pending','queued')
	`
	tag, err := r.pool.Exec(ctx, q, id)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return ErrNotFound
	}
	return nil
}

// FetchDue claims up to limit pending jobs whose run_at is now-or-past, in a
// single transaction. The rows are locked FOR UPDATE SKIP LOCKED so multiple
// scheduler replicas can run concurrently without stepping on each other.
//
// The returned jobs are *not* yet transitioned — the caller publishes them to
// Kafka and then calls MarkQueued. If publishing fails, the row remains
// 'pending' and a later scan will pick it up again.
func (r *Repo) FetchDue(ctx context.Context, limit int) ([]*job.Job, error) {
	const q = `
		SELECT id, queue, job_type, priority, state, payload,
		       dedup_key, dedup_mode, retry_policy, attempts, last_error,
		       run_at, visibility_until, claimed_by,
		       created_at, updated_at, completed_at, result
		FROM jobs
		WHERE state = 'pending' AND run_at <= NOW()
		ORDER BY run_at
		LIMIT $1
		FOR UPDATE SKIP LOCKED
	`
	tx, err := r.pool.BeginTx(ctx, pgx.TxOptions{})
	if err != nil {
		return nil, err
	}
	defer func() { _ = tx.Rollback(ctx) }()

	rows, err := tx.Query(ctx, q, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var jobs []*job.Job
	for rows.Next() {
		j, err := scanJob(rows)
		if err != nil {
			return nil, err
		}
		jobs = append(jobs, j)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}
	return jobs, nil
}

// ReclaimExpiredLeases finds running jobs whose visibility lease elapsed and
// pushes them back into pending so they can be retried by another worker.
// Returns the number of jobs reclaimed.
func (r *Repo) ReclaimExpiredLeases(ctx context.Context, limit int) (int, error) {
	const q = `
		WITH expired AS (
			SELECT id FROM jobs
			WHERE state = 'running'
			  AND visibility_until IS NOT NULL
			  AND visibility_until < NOW()
			ORDER BY visibility_until
			LIMIT $1
			FOR UPDATE SKIP LOCKED
		)
		UPDATE jobs
		SET state = 'pending',
		    run_at = NOW(),
		    last_error = COALESCE(last_error, '') || ' [reclaimed: lease expired]',
		    visibility_until = NULL,
		    claimed_by = NULL,
		    updated_at = NOW()
		FROM expired
		WHERE jobs.id = expired.id
	`
	tag, err := r.pool.Exec(ctx, q, limit)
	if err != nil {
		return 0, err
	}
	return int(tag.RowsAffected()), nil
}

// QueueStats is a per-(queue,priority) snapshot used by the stats endpoint
// and to feed dashboard gauges.
type QueueStats struct {
	Queue    string `json:"queue"`
	Priority string `json:"priority"`
	State    string `json:"state"`
	Count    int64  `json:"count"`
}

// Stats returns a fan-out of job counts grouped by queue/priority/state.
func (r *Repo) Stats(ctx context.Context) ([]QueueStats, error) {
	const q = `
		SELECT queue, priority, state, COUNT(*)
		FROM jobs
		GROUP BY queue, priority, state
		ORDER BY queue, priority, state
	`
	rows, err := r.pool.Query(ctx, q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []QueueStats
	for rows.Next() {
		var s QueueStats
		if err := rows.Scan(&s.Queue, &s.Priority, &s.State, &s.Count); err != nil {
			return nil, err
		}
		out = append(out, s)
	}
	return out, rows.Err()
}

// OldestPendingAges returns the age in seconds of the oldest pending job per
// priority — used by autoscaling signals.
func (r *Repo) OldestPendingAges(ctx context.Context) (map[string]float64, error) {
	const q = `
		SELECT priority, EXTRACT(EPOCH FROM (NOW() - MIN(run_at)))
		FROM jobs
		WHERE state IN ('pending','queued')
		GROUP BY priority
	`
	rows, err := r.pool.Query(ctx, q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := map[string]float64{}
	for rows.Next() {
		var p string
		var age float64
		if err := rows.Scan(&p, &age); err != nil {
			return nil, err
		}
		out[p] = age
	}
	return out, rows.Err()
}

// List returns recent jobs filtered by queue/state, ordered newest-first.
func (r *Repo) List(ctx context.Context, queue, state string, limit int) ([]*job.Job, error) {
	if limit <= 0 || limit > 500 {
		limit = 50
	}
	var (
		conds []string
		args  []any
	)
	if queue != "" {
		args = append(args, queue)
		conds = append(conds, fmt.Sprintf("queue = $%d", len(args)))
	}
	if state != "" {
		args = append(args, state)
		conds = append(conds, fmt.Sprintf("state = $%d", len(args)))
	}
	where := ""
	if len(conds) > 0 {
		where = "WHERE " + strings.Join(conds, " AND ")
	}
	args = append(args, limit)

	q := fmt.Sprintf(`
		SELECT id, queue, job_type, priority, state, payload,
		       dedup_key, dedup_mode, retry_policy, attempts, last_error,
		       run_at, visibility_until, claimed_by,
		       created_at, updated_at, completed_at, result
		FROM jobs %s
		ORDER BY created_at DESC
		LIMIT $%d
	`, where, len(args))

	rows, err := r.pool.Query(ctx, q, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []*job.Job
	for rows.Next() {
		j, err := scanJob(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, j)
	}
	return out, rows.Err()
}

// rowScanner is satisfied by both pgx.Row and pgx.Rows.
type rowScanner interface {
	Scan(dest ...any) error
}

func scanJob(row rowScanner) (*job.Job, error) {
	var (
		j         job.Job
		retryRaw  []byte
	)
	if err := row.Scan(
		&j.ID, &j.Queue, &j.JobType, &j.Priority, &j.State, &j.Payload,
		&j.DedupKey, &j.DedupMode, &retryRaw, &j.Attempts, &j.LastError,
		&j.RunAt, &j.VisibilityUntil, &j.ClaimedBy,
		&j.CreatedAt, &j.UpdatedAt, &j.CompletedAt, &j.Result,
	); err != nil {
		return nil, err
	}
	if len(retryRaw) > 0 {
		if err := json.Unmarshal(retryRaw, &j.RetryPolicy); err != nil {
			return nil, fmt.Errorf("decode retry policy: %w", err)
		}
	}
	return &j, nil
}
